AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.stockcrowd.serverless::serverless-example-integration
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ServerlessExampleIntegrationApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.stockcrowd.serverless.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/serverless-example-integration-0.0.1-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ServerlessExampleIntegrationApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/integration1'
    Export:
      Name: ServerlessExampleIntegrationApi
